name: Main
on:
  push:
jobs:
  build:
    name: 'Go Build (1.24)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - run: 'GOBIN=$PWD/bin go install -v ./cmd/...'
  static:
    name: 'Go Static (1.24)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: "Prepare: staticcheck"
        run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - run: 'go vet ./cmd/...'
      - run: 'staticcheck ./cmd/...'
  tests:
    name: 'Go Tests (1.24)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: "Prepare: gotestsum"
        run: 'go install gotest.tools/gotestsum@latest'
      - run: 'gotestsum --format testname'
